### ISSUE TITLE
Seta symbol X1-006 - wrong pin number for /WR pin nr 47

### ISSUE THREAD

**Issue by skutis** [jotego/jtkicad#10]
![image](https://user-images.githubusercontent.com/80739822/202282854-36c9a901-f7da-4a31-b345-31a1225719af.png)

Pin /WR is number 47, not 48. Please correct it.

**Comment by etriana85** [comment]
It is already corrected. please check.
![006](https://user-images.githubusercontent.com/92724765/202422955-bfce241f-f52b-4a24-8d28-4efa9f30ac1e.png)
