### ISSUE TITLE
74LS157

### ISSUE THREAD

**Issue by antongale** [jotego/jtkicad#11]
Channel C & D are swapped in the library for the 74LS157.

IOc should be 11 (not 14)
IOd should be 14 (not 11)

I1c should be 10 (not 13)
I1d should be 13 (not 10)

Zc should be 9 (not 12)
Zd should be 12 (not 9)

**Comment by jotego** [comment]
@etriana85 could you check this, please?

**Comment by etriana85** [comment]
Issue resolved. I have reviewed the datasheet and corrected the connections.

**Comment by etriana85** [comment]
![74ls157#11](https://user-images.githubusercontent.com/92724765/213992599-d7560d61-ca9d-4928-86ad-408f2656d40d.png)
