### ISSUE TITLE
RAM_5501 has incorrect pin labelling for D3

### ISSUE THREAD

**Issue by antongale** [jotego/jtkicad#12]
RAM_5501 pin 15 is labelled D4, it should be labelled D3.  

This is the same footprint as a AM93422 which is found in the TAITO SJ system.

**Comment by jotego** [comment]
@etriana85 Could you check it, please?

**Comment by etriana85** [comment]
The name of the pin in the symbol RAM_5501 has been corrected
![#12](https://user-images.githubusercontent.com/92724765/215493649-26358d95-fcfd-47d2-9526-864d8ad589f6.png)
