### ISSUE TITLE
Add 74LS25

### ISSUE THREAD

**Issue by antongale** [jotego/jtkicad#13]
Could you add the 74LS25 to the jt74.kicad_sym library?  Code below:

  (symbol "74LS25" (pin_names (offset 1.016)) (in_bom yes) (on_board yes)
    (property "Reference" "U" (id 0) (at 1.27 7.62 0)
      (effects (font (size 1.27 1.27)))
    )
    (property "Value" "74LS25" (id 1) (at 0 -5.08 0)
      (effects (font (size 1.27 1.27)))
    )
    (property "Footprint" "" (id 2) (at 0 1.27 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (property "Datasheet" "https://www.ti.com/lit/gpn/sn7425" (id 3) (at -1.27 1.27 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (property "ki_locked" "" (id 4) (at 0 0 0)
      (effects (font (size 1.27 1.27)))
    )
    (property "ki_keywords" "TTL Nor4" (id 5) (at 0 0 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (property "ki_description" "Dual 4-input NOR with strobe" (id 6) (at 0 0 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (property "ki_fp_filters" "DIP?14*" (id 7) (at 0 0 0)
      (effects (font (size 1.27 1.27)) hide)
    )
    (symbol "74LS25_1_1"
      (arc (start -5.5634 -3.81) (mid -3.94 1.27) (end -5.5634 6.35)
        (stroke (width 0.254) (type default) (color 0 0 0 0))
        (fill (type none))
      )
      (arc (start -1.7534 -3.81) (mid 2.2002 -2.2433) (end 4.5966 1.27)
        (stroke (width 0.254) (type default) (color 0 0 0 0))
        (fill (type background))
      )
      (polyline
        (pts
          (xy -5.5634 -3.81)
          (xy -1.7534 -3.81)
        )
        (stroke (width 0.254) (type default) (color 0 0 0 0))
        (fill (type background))
      )
      (polyline
        (pts
          (xy -5.5634 6.35)
          (xy -1.7534 6.35)
        )
        (stroke (width 0.254) (type default) (color 0 0 0 0))
        (fill (type background))
      )
      (polyline
        (pts
          (xy -1.7534 6.35)
          (xy -5.5634 6.35)
          (xy -4.7787 5.0818)
          (xy -4.3452 3.9148)
          (xy -4.0118 2.5477)
          (xy -3.9284 1.3307)
          (xy -3.9451 0.5139)
          (xy -4.0952 -0.5697)
          (xy -4.2934 -1.27)
          (xy -4.762 -2.437)
          (xy -5.5634 -3.81)
          (xy -1.7534 -3.81)
        )
        (stroke (width -25.4) (type default) (color 0 0 0 0))
        (fill (type background))
      )
      (arc (start 4.5966 1.27) (mid 2.2105 4.7961) (end -1.7534 6.35)
        (stroke (width 0.254) (type default) (color 0 0 0 0))
        (fill (type background))
      )
      (pin input line (at -8.89 5.08 0) (length 4)
        (name "~" (effects (font (size 1.27 1.27))))
        (number "1" (effects (font (size 1.27 1.27))))
      )
      (pin input line (at -8.89 2.54 0) (length 4.75)
        (name "~" (effects (font (size 1.27 1.27))))
        (number "2" (effects (font (size 1.27 1.27))))
      )
      (pin input line (at -1.27 10.16 270) (length 3.8)
        (name "G" (effects (font (size 1.27 1.27))))
        (number "3" (effects (font (size 1.27 1.27))))
      )
      (pin input line (at -8.89 0 0) (length 4.75)
        (name "~" (effects (font (size 1.27 1.27))))
        (number "4" (effects (font (size 1.27 1.27))))
      )
      (pin input line (at -8.89 -2.54 0) (length 4)
        (name "~" (effects (font (size 1.27 1.27))))
        (number "5" (effects (font (size 1.27 1.27))))
      )
      (pin output inverted (at 8.89 1.27 180) (length 4.25)
        (name "Y" (effects (font (size 1.27 1.27))))
        (number "6" (effects (font (size 1.27 1.27))))
      )
    )

**Comment by antongale** [comment]
I didn't do a very good job on this symbol apparently as the pins don't snap to the grid.  I'm sure you guys can work your magic, but I can made the modifications and re-post if you like.

**Comment by etriana85** [comment]
I'll check it and let you know

**Comment by etriana85** [comment]
All Right.
![#13](https://user-images.githubusercontent.com/92724765/218672591-7483953c-dd5e-4d01-a862-eea2d4dd7f45.png)

**Comment by jotego** [comment]
Thank you. I think the VCC pin is off grid

**Comment by etriana85** [comment]
![issue#13](https://user-images.githubusercontent.com/92724765/218673337-54529f3f-e465-416c-873f-c59fcff11e3d.png)

**Comment by etriana85** [comment]
Yeah, it looks kind of weird, but it's aligned. It must be the angle of the photograph.

**Comment by etriana85** [comment]
![#13](https://user-images.githubusercontent.com/92724765/218673986-977917ea-0769-40ee-b125-3acf2284ae67.png)
