### ISSUE TITLE
 uPD7759 - add background color

### ISSUE THREAD

**Issue by skutis** [jotego/jtkicad#6]
![image](https://user-images.githubusercontent.com/80739822/200892765-f4eacac7-cc87-448b-b9a3-bf0ac3e6e6fd.png)

The uPD7759 in the arcade library does not have any background color. Please add it.

**Comment by etriana85** [comment]
skutis, check the symbol μPD7759.
Remember to pull from the terminal, so that it is updated in your kicad. Please search for it as μPD7759, or simply as PD7759.
I have added the link to the data sheet, I have put some description of the symbol and I have put the fill.
