### ISSUE TITLE
Create a new symbol for PAL16L8?

### ISSUE THREAD

**Issue by skutis** [jotego/jtkicad#9]
It would be a good idea to create a new symbol for, for instance in the "arcade" library.
- The existing symbol specifies pins 12 and 19 as I/O although they are only outputs for PAL16L8
- The existing symbol is unnecessarily large
- VCC and GND pins on the sides and not on the top for cleaner schematics. 

This is the existing symbol in the KiCad "Logic_programmable" library
![image](https://user-images.githubusercontent.com/80739822/201436317-31fb5e08-1015-46ea-a27e-b5dd8928a059.png)

This is the one I have created, but not commited yet.
![image](https://user-images.githubusercontent.com/80739822/201436442-41d5a988-d3b5-4f65-8ca1-48af104286d4.png)

If you think this is a good idea I can commit the one I have made.
The datasheet for PAL16L8 is here: https://www.ti.com/lit/gpn/pal16r6am

**Comment by etriana85** [comment]
Hello Skutis, as you mention, there is already a PAL16L8 symbol, by default in the kicad library. Your idea is good, but before making another symbol that is already available in kicad, I'll check with Jotego. I will keep you informed.

**Comment by skutis** [comment]
- OK
- That is fine
- Actually the input number in the name might be confusing. In the PLD files they refer to pin number not input number or output number. But that is ok.
- If you wish to keep the supply pins on the top or bottom that is ok. Just wanted to share my opinion on it. It is best to keep every pin visible.
- I think it is a bad idea to avoid using the correct type for a pin just to avoid ERC errors. Eventually you might loose the whole point of having ERC then. But, I might be not see the whole picture here and I'll agree with your comment.
- Bubbles are ok.

Esperanza will you create the symbol?

**Comment by jotego** [comment]
The thing is that all pins still have the tri-state buffer:
![imagen](https://user-images.githubusercontent.com/1863036/201855082-316c774d-2656-409f-b974-764c4a1d659a.png)
That's why we cannot just use bidirectional. I think bidirectional does not cater for the high-impedance case.
About the pin names, what did **MAME's jedutil** use to report? I think whatever they do to name the pin signals, we should follow that as we copy the equations from that tools.

**Comment by skutis** [comment]
Ok. I think jedutil uses the physical pins for numbering.

**Comment by etriana85** [comment]
Hi!,
According to the request, the new symbol PAL16L8' is now available, in the Texas Instruments bookstore.

**Comment by jotego** [comment]
@etriana85 can you paste a snapshot of the new symbol here so we can see it?
